### ISSUE TITLE
telethon.errors.rpcerrorlist.ApiIdInvalidError: The api_id/api_hash combination is invalid (caused by SendCodeRequest )

### ISSUE THREAD

**Issue by ghost** [N4rr34n6/TgUserDetails#1]
Im getting this error!

How to fix please???

**Comment by N4rr34n6** [comment]
Hello,

The error telethon.errors.rpcerrorlist.ApiIdInvalidError: The api_id/api_hash combination is invalid (caused by SendCodeRequest) indicates that the combination of api_id and api_hash you are using is not valid.

These values are unique for each application and are obtained by registering your application on My Telegram. Here are the steps to obtain them:

    Go to https://my.telegram.org/ and log in with your phone number.
    Click on 'API development tools' and fill out the form.
    You will get the api_id and api_hash for your application.
    Please make sure to replace the api_id and api_hash values in your code with the ones you obtained in the previous step. 

Here's an example of how it should look:

api_id = 1234567 # replace 1234567 with your api_id
api_hash = 'abcdef1234567890abcdef1234567890' # replace 'abcdef1234567890abcdef1234567890' with your api_hash

I hope this resolves your issue. If you have any further questions, feel free to ask.

Regards,
Marcos.-

**Comment by ghost** [comment]
I do it everything, still not working bro!

**Comment by N4rr34n6** [comment]
Hello,

I'm sorry to hear that you're still experiencing issues. In order to assist you more effectively, I'll need some additional information about the error you're encountering.

Please provide the complete error message you're receiving. If possible, a screenshot of the error would also be very helpful. This will help us better understand the problem and find a suitable solution.

Additionally, make sure you're using the latest version of the Telethon library and that your Python environment is properly configured. Also, check that the .session file is present in the same directory as your script and that it has the correct read and write permissions.

I look forward to your response.

Regards, Marcos.-

**Comment by ghost** [comment]
Oh man! Yeah i finally made it! Thanks a lot bro! A quick question , can i verify a list of numbers to get the id in bulk? I mean, maybe do the command -p +XXXXXX , but add more numbers to get the ID? or just one by one?
